# Generated by Django 4.2 on 2023-04-07 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_department_head'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Работник', 'verbose_name_plural': 'Работники'},
        ),
        migrations.AddField(
            model_name='note',
            name='count_of_notify',
            field=models.IntegerField(default=0, verbose_name='Количество отправленных уведомлений'),
        ),
        migrations.AlterField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='head_department', to='backend.employee', verbose_name='Глава отдела'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='department_employers', to='backend.department', verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(default='Сотрудник', on_delete=django.db.models.deletion.DO_NOTHING, related_name='employers', to='backend.role', to_field='name', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='note',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee_notes', to='backend.employee', verbose_name='Сотрудник'),
        ),
    ]
