# Generated by Django 4.2 on 2023-04-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_employee_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='invite_link',
            field=models.CharField(default=' ', max_length=128, verbose_name='Инвайт ссылка'),
            preserve_default=False,
        ),
    ]
