# Generated by Django 4.2 on 2023-04-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_employee_invite_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='invite_link',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Инвайт ссылка'),
        ),
    ]
