# Generated by Django 4.2 on 2023-04-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_employee_invite_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='deadline_lost',
            field=models.BooleanField(default=True, verbose_name='Дэдлайн не просрочен'),
        ),
    ]
