# Generated by Django 4.2 on 2023-04-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_note_deadline_lost'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='count_deadline_lost',
            field=models.IntegerField(default=0, verbose_name='Количество просрочек'),
        ),
        migrations.AddField(
            model_name='department',
            name='total_notes_count',
            field=models.IntegerField(default=0, verbose_name='Количество записей'),
        ),
    ]
