# Generated by Django 4.2 on 2023-04-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_department_count_deadline_lost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='total_notes_count',
            field=models.IntegerField(default=0, verbose_name='Количество всех записей'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='count_of_lost_deadline',
            field=models.IntegerField(default=0, verbose_name='Количество просрочек'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='total_count',
            field=models.IntegerField(default=0, verbose_name='Всего записей'),
        ),
    ]
