# Generated by Django 4.2 on 2023-04-10 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_department_total_notes_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='head',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='head_department', to='backend.employee', verbose_name='Глава отдела'),
        ),
    ]
