# Generated by Django 4.2 on 2023-04-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_department_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='not_filled_now',
            field=models.IntegerField(default=0, verbose_name='Количество не заполненных на данный момент'),
        ),
    ]
