# Generated by Django 4.2 on 2023-04-10 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_employee_not_filled_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='count_not_filled_notes',
            field=models.IntegerField(default=0, verbose_name='Незаполненно на текущий момент'),
        ),
        migrations.AlterField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='head_department', to='backend.employee', verbose_name='Глава отдела'),
        ),
    ]
