# Generated by Django 4.2 on 2023-04-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_department_ill_found_count_employee_ill_found_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='notification',
            field=models.BooleanField(default=False, verbose_name='Уведомление о положительном результате'),
        ),
    ]
