# Generated by Django 4.2 on 2023-04-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_note_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='nsi_frmo',
            field=models.CharField(default='', max_length=300, verbose_name='НСИ ФРМО'),
        ),
    ]
