# Generated by Django 4.2 on 2023-04-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_alter_note_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='first_notification',
            field=models.BooleanField(default=False, verbose_name='Уведомление о постановке задачи'),
        ),
    ]
